config/routes.rb
Rails.application.routes.draw do
  # resources :categories
  devise_for :admins
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  # resources :comments, only: [:index, :show]
  resources :articles, only: [:index]
  root to: "articles#index"
  get "/:category_name", to: "articles#index"
  get "/:category_name/:id", to: "articles#show"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActionText::Attribute
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :admin, optional: true
  belongs_to :category
  has_many :comments
  mount_uploader :image, ImageUploader
  validates_presence_of :content, :title
  before_validation :generate_metadata
  enum status: [:escrevendo, :publicado]
  has_rich_text :content
  has_rich_text :highlight

  def default_values
  end

  def generate_metadata(c = 1)
    if self.title_changed? || self.new_record?
      metadata = self.title.gsub(" ", "_").downcase
      metadata = c === 1 ? metadata : "#{metadata}#{c}"
      return generate_metadata(c + 1) if Article.find_by(metadata: metadata)
      self.metadata = metadata
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :comment, optional: true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = params[:category_name] ? Category.find_by(name: params[:category_name].gsub("_", " ").titleize)&.articles : Article
    @articles = @articles ? @articles.order(published_at: :asc) : []
  end

  def show
    begin
      @articles = Category.find_by(name: params[:category_name]).articles.order(published_at: :asc)
      @article = @articles.find_by(id: params[:id])
      @options = {
        next: @articles[@articles.index(@article) + 1],
        previous: @articles[@articles.index(@article) - 1],
      }
    rescue
      redirect_to "/", notice: "Erro ao abrir esse artigo"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:name, :content, :article_id, :comment_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_fit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/index.html.erb
<div class="s-content">
    <div class="masonry-wrap">
        <div class="masonry">
            <div class="grid-sizer"></div>
            <% @articles.each do |article| %>
              <article class="masonry__brick entry format-standard ">
                  <% if article.image.url %>
                    <div class="entry__thumb">
                        <a href="single-standard.html" class="entry__thumb-link">
                            <%= image_tag article.image_url %> 
                        </a>
                    </div>
                  <% end %>
  
                  <div class="entry__text">
                      <div class="entry__header">

                          <h2 class="entry__title"><%= link_to article.title, "/#{article.category.name}/#{article.id}" %></h2>
                          <div class="entry__meta">
                              <span class="entry__meta-cat">
                                  <%= article.category_id %>
                              </span>
                              
                              <span class="entry__meta-date">
                                  <a href="single-standard.html"><%= I18n.l(article.published_at || Time.now, format: :long) %></a>
                              </span>
                          </div>
                          
                      </div>
                      <div class="entry__excerpt max-length">
                        <%= raw article.highlight %>
                      </div>
                      <div class="entry__excerpt max-length">
                        <%= link_to "Ver mais", "/#{article.category.name}/#{article.id}" %>
                      </div>
                  </div>
              </article>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/show.html.erb
        <div class="s-content content">
            <main class="row content__page">
                
                <article class="column large-full entry format-standard">
                    <% if @article.image&.url %>
                      <div class="media-wrap entry__media">
                          <div class="entry__post-thumb">
                              <img src=<%= @article.image&.url %> sizes="(max-width: 2000px) 100vw, 2000px" alt="">
                          </div>
                      </div>
                    <% end %>

                    <div class="content__page-header entry__header">
                        <h1 class="display-1 entry__title">
                        <%= @article.title %>
                        </h1>
                        <ul class="entry__header-meta">
                            <li class="author">Por <a href="#0"><%= @article.admin ? @article.admin.name : "Anonimo" %></a></li>
                            <li class="date"><%= I18n.l((@article.published_at || DateTime.now), format: :long) %></li>
                            <li class="cat-links">
                                <%= link_to @article.category.name, "/#{@article.category.name}" %>
                            </li>
                        </ul>
                    </div> 

                    <div class="entry__content">
                        <%= raw @article.content %>
                    </div> 
                    <% if @options["previous"] || @options["next"] %>
                      <div class="entry__pagenav">
                          <div class="entry__nav">
                              <% if @options["previous"] %>
                                <div class="entry__prev">
                                    <a href="#0" rel="prev">
                                        <span>Anterior</span>
                                        <%= link_to @options["previous"]["title"], "/#{@options["previous"]["metadata"]}" %>
                                    </a>
                                </div>
                              <% end %>
                              <% if @options["next"] %>
                                <div class="entry__next">

                                    <a href="#0" rel="next">
                                        <span>Proximo</span>
                                        <%= link_to @options["next"]["title"], "/#{@options["next"]["metadata"]}" %>
                                    </a>
                                </div>
                              <% end %>
                          </div>
                      </div> 
                    <% end %>
                </article>
                <%= render template: "comments/index" %>
            </main>

        </div> 

app/views/comments/index.html.erb
<% if @article&.comments&.size > 0 %>
  <div class="comments-wrap">
    <div id="comments" class="column large-12">

      <h3 class="h2"><%= @article.comments.size %> Comentários</h3>
      <ol class="commentlist">
        <% @article.comments.each do |comment| %>
        <li class="thread-alt depth-1 comment">

          <div class="comment__content">

            <div class="comment__info">
              <div class="comment__author"><%= comment.name %></div>

              <div class="comment__meta">
                <div class="comment__time"><%= I18n.l(comment.created_at, format: :short) %></div>
              </div>
            </div>

            <div class="comment__text">
              <%= raw comment.content %>
            </div>

          </div>
          <% if comment.comments.size > 0 %>
          <ul class="children">

            <li class="depth-2 comment">

              <div class="comment__avatar">
                <img class="avatar" src="images/avatars/user-03.jpg" alt="" width="50" height="50">
              </div>

              <div class="comment__content">

                <div class="comment__info">
                  <div class="comment__author">Kakashi Hatake</div>

                  <div class="comment__meta">
                    <div class="comment__time">April 29, 2019</div>
                    <div class="comment__reply">
                      <a class="comment-reply-link" href="#0">Reply</a>
                    </div>
                  </div>
                </div>

                <div class="comment__text">
                  <p>Duis sed odio sit amet nibh vulputate
                    cursus a sit amet mauris. Morbi accumsan ipsum velit. Duis sed odio sit amet nibh vulputate
                    cursus a sit amet mauris</p>
                </div>

              </div>

              <ul class="children">

                <li class="depth-3 comment">

                  <div class="comment__avatar">
                    <img class="avatar" src="images/avatars/user-04.jpg" alt="" width="50" height="50">
                  </div>

                  <div class="comment__content">

                    <div class="comment__info">
                      <div class="comment__author">John Doe</div>

                      <div class="comment__meta">
                        <div class="comment__time">April 29, 2019</div>
                        <div class="comment__reply">
                          <a class="comment-reply-link" href="#0">Reply</a>
                        </div>
                      </div>
                    </div>

                    <div class="comment__text">
                      <p>Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est
                        etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.</p>
                    </div>

                  </div>

                </li>

              </ul>

            </li>

          </ul>
          <% end %>

        </li>
        <% end %>
      </ol>


    </div>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="menu">
        <a href="#" data-target="slide-out" class="sidenav-trigger"><%= fa_icon "bars", class: "fa-2x" %></a>
    </div>
    <div id="top" class="s-wrap site-wrapper">
        <ul id="slide-out" class="sidenav sidenav-fixed">
            <li><div class="user-view">
            <%= link_to "ARTHUR MOURA", "/", class: "home-title" %>
            </div></li>
            <% if current_admin %>
              <li><%= link_to "Admin", "/admin" %> </li>
            <% end %>
            <li class=<%= current_page?("/") ? "active" : "" %>><%= link_to "Home", "/" %></li>
            <% Category.all.each do |category| %>
              <li class=<%= current_page?("/#{category.path}") ? "active" : "" %>><%= link_to "#{category.name}", "/#{category.path}" %></li>
            <% end %>
            <li class=<%= current_page?("sobre") ? "active" : "" %>><%= link_to "Sobre", "/sobre" %></li>
            <li>
                <a href="https://facebook.com/arthurjmoura" target="_blank">
                    <%= fa_icon "facebook-square", class: "fa-2x favi-padding" %>
                </a>
            </li>
            <li>
                <a href="https://twitter.com/arthurjm95" target="_blank">
                    <%= fa_icon "twitter", class: "fa-2x favi-padding" %>
                </a>
            </li>
            <li>
                <a href="https://instagram.com/arthurjmoura" target="_blank">
                    <%= fa_icon "instagram", class: "fa-2x favi-padding" %>
                </a>
            </li>   
        </ul>
        <%= yield %>
    </div> 
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>